export const LOAD_ALL_GAME_SUCCESS = 'LOAD_ALL_GAME_SUCCESS';
export const SAVE_ALL_GAME_SUCCESS = 'SAVE_ALL_GAME_SUCCESS';
export const LOAD_RESULT_BY_CORRECT_ANSWERS = 'LOAD_RESULT_BY_CORRECT_ANSWERS';
